[project]
name = "aid-labs"
version = "0.1.0"
description = "Laboratorios de Análisis Inteligente de Datos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
